version: '3.8'

services:

  productapi:
    container_name: productapi

    build:
      context: .
      dockerfile: ProductAPI/Dockerfile

    ports:
      - "5000:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=.;Database=ProductDb;Trusted_Connection=True;;TrustServerCertificate=True;Encrypt=False"

    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    container_name: productdb

    # environment:
    #   ACCEPT_EULA: "Y"
    #   SA_PASSWORD: "YourStrong@Pass123"

    ports:
      - "1433:1433"

    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: